# Generated by Django 4.0.4 on 2022-06-08 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Temperatura', 'Temperatura'), ('PM10', 'Pm10')], default='Temperatura', max_length=20)),
                ('indirizzo', models.CharField(max_length=30)),
                ('cap', models.IntegerField(help_text='5 numeri')),
            ],
        ),
        migrations.CreateModel(
            name='Rilevamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Temperatura', 'Temperatura'), ('PM10', 'Pm10')], default='Temperatura', max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 8, 11, 34, 42, 535302))),
                ('valore', models.FloatField()),
                ('sensore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_monitor.sensori')),
            ],
        ),
    ]
