# Generated by Django 4.0.4 on 2022-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rilevamenti',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
