# Generated by Django 4.0.5 on 2022-06-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Temperature', 'Temperature'), ('PM10', 'PM10')], max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('CAP', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Temperature', 'Temperature'), ('PM10', 'PM10')], max_length=15)),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('value', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_monitor.sensor')),
            ],
        ),
    ]
